// CANONICAL BSN program data — this file is the editable source of truth for the
// seed. Edit entries here (fill in verified requirements, add new schools), then run
// `npx tsx prisma/seed.ts` to push to the DB (idempotent upsert by `slug`).
//
// For the school-research routine, see docs/AGENT_ROUTINE.md. Field notes:
//   slug            stable key: `<state>-<university>-<city>` lowercased, non-alnum -> '-'
//   tier            'Local' | 'Top TX' | 'Top US'   region 'Arkansas' | 'Texas' | 'National'
//   requiredCourses array of course KEYS (not labels): ANAT_PHYS_1, ANAT_PHYS_2, MICRO,
//                   CHEM, STATS, NUTRITION, LIFESPAN, ENGLISH_COMP  (see lib/constants.ts)
//   examType        'TEAS' | 'HESI A2' | 'NLN PAX' | null   minExamScore = percent (0-100)
//   minOverallGPA / minScienceGPA   0.0-4.0 or null if unverified
//   dataQuality     'verified' | 'partial' | 'placeholder'
//                   verified   = confirmed directly from official program page
//                   partial    = sourced from published info but may be stale; spot-check before applying
//                   placeholder = no requirement data yet; fit scores are exploratory estimates only
export type SeedProgram = {
  slug: string; name: string; university: string; city: string; state: string
  isPublic: boolean; programType: string; isFlagship: boolean
  tier: 'Local' | 'Top TX' | 'Top US'; region: 'Arkansas' | 'Texas' | 'National'
  minOverallGPA: number | null; minScienceGPA: number | null; requiredCourses: string[]
  examType: string | null; minExamScore: number | null; casperRequired: boolean
  deadlines: string | null; notes: string | null
  dataQuality: 'verified' | 'partial' | 'placeholder'
}

export const SEED_PROGRAMS: SeedProgram[] = [
  { slug: "ar-arkansas-state-university-jonesboro", name: "BSN Program", university: "Arkansas State University", city: "Jonesboro", state: "AR", isPublic: true, programType: "Traditional BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: 3, minScienceGPA: 3, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","STATS","ENGLISH_COMP"], examType: "TEAS", minExamScore: null, casperRequired: false, deadlines: "Verify with ASU School of Nursing", notes: "3.0 cumulative and prerequisite GPA required (official). TEAS required; minimum score not published. Verify current details with the ASU School of Nursing.", dataQuality: "partial" },
  { slug: "ar-arkansas-tech-university-russellville", name: "BSN Program", university: "Arkansas Tech University", city: "Russellville", state: "AR", isPublic: true, programType: "Traditional BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: 2.75, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS"], examType: "TEAS", minExamScore: null, casperRequired: false, deadlines: "Feb 15 (Fall) / Sep 15 (Spring)", notes: "Prerequisite GPA ≥ 2.75. TEAS required at the 'Proficient' level (≈59%+); ATU uses the TEAS, not the HESI. Verified from the official admission page (2026).", dataQuality: "partial" },
  { slug: "ar-harding-university-searcy", name: "BSN Program", university: "Harding University", city: "Searcy", state: "AR", isPublic: false, programType: "Traditional BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: 3, minScienceGPA: 3, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS","NUTRITION","LIFESPAN","ENGLISH_COMP"], examType: null, minExamScore: null, casperRequired: true, deadlines: "January 15 for Fall admission", notes: "Private Christian university. CASPer used for holistic review. Data is approximate — verify with Harding.", dataQuality: "partial" },
  { slug: "ar-henderson-state-university-arkadelphia", name: "BSN Program", university: "Henderson State University", city: "Arkadelphia", state: "AR", isPublic: true, programType: "Traditional BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: 2.5, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","STATS"], examType: "TEAS", minExamScore: 55, casperRequired: false, deadlines: "March 15 for Fall admission", notes: "One of the more accessible programs in Arkansas. Verify with Henderson Department of Nursing.", dataQuality: "partial" },
  { slug: "ar-southern-arkansas-university-magnolia", name: "BSN Program", university: "Southern Arkansas University", city: "Magnolia", state: "AR", isPublic: true, programType: "Traditional BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: 2.5, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","ENGLISH_COMP"], examType: "TEAS", minExamScore: 55, casperRequired: false, deadlines: "April 1 for Fall admission", notes: "Data is approximate. Verify with SAU School of Nursing.", dataQuality: "partial" },
  { slug: "ar-university-of-arkansas-fayetteville", name: "Pre-Licensure BSN", university: "University of Arkansas", city: "Fayetteville", state: "AR", isPublic: true, programType: "Traditional BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: 3, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","ENGLISH_COMP"], examType: "TEAS", minExamScore: null, casperRequired: true, deadlines: "Jan 15 (Fall) / July 15 (Spring), via NursingCAS", notes: "Eleanor Mann School of Nursing. TEAS and Casper required; admission is competitive (admits typically score ~70+ on the TEAS). Uses College Algebra rather than statistics. Verified from the official admission page (2026).", dataQuality: "verified" },
  { slug: "ar-university-of-arkansas-for-medical-sciences-uams-little-rock", name: "Traditional BSN", university: "University of Arkansas for Medical Sciences (UAMS)", city: "Little Rock", state: "AR", isPublic: true, programType: "Traditional BSN", isFlagship: true, tier: "Local", region: "Arkansas", minOverallGPA: 2.5, minScienceGPA: 2.5, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS","NUTRITION","LIFESPAN","ENGLISH_COMP"], examType: "TEAS", minExamScore: 60, casperRequired: false, deadlines: "March 1", notes: "UAMS College of Nursing. TEAS minimum 60% (waived when both cumulative and prerequisite GPA are ≥ 3.4). Flagship academic medical center. Verified from the official admission page (2026).", dataQuality: "verified" },
  { slug: "ar-university-of-central-arkansas-conway", name: "Traditional BSN", university: "University of Central Arkansas", city: "Conway", state: "AR", isPublic: true, programType: "Traditional BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: 2.75, minScienceGPA: 2.5, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS","NUTRITION","LIFESPAN","ENGLISH_COMP"], examType: null, minExamScore: null, casperRequired: false, deadlines: "Feb 15 – Mar 15 (one application cycle per year)", notes: "UCA Department of Nursing. No TEAS/HESI entrance exam required. Requires a grade of C or better in all prerequisites. Verified from the official admission page (2026).", dataQuality: "verified" },
  { slug: "ar-john-brown-university-siloam-springs", name: "BSN", university: "John Brown University", city: "Siloam Springs", state: "AR", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "ar-ouachita-baptist-university-arkadelphia", name: "BSN", university: "Ouachita Baptist University", city: "Arkadelphia", state: "AR", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "ar-philander-smith-university-little-rock", name: "BSN", university: "Philander Smith University", city: "Little Rock", state: "AR", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "Dr. Joycelyn Elders School of Allied and Public Health", dataQuality: "placeholder" },
  { slug: "ar-university-of-arkansas-fort-smith-fort-smith", name: "BSN", university: "University of Arkansas - Fort Smith", city: "Fort Smith", state: "AR", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "Carolyn McKelvey Moore School of Nursing", dataQuality: "placeholder" },
  { slug: "ar-university-of-arkansas-at-monticello-monticello", name: "BSN", university: "University of Arkansas at Monticello", city: "Monticello", state: "AR", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "ar-university-of-arkansas-at-pine-bluff-pine-bluff", name: "BSN", university: "University of Arkansas at Pine Bluff", city: "Pine Bluff", state: "AR", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Arkansas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "ar-university-of-arkansas-for-medical-sciences-northwest-fayetteville", name: "Accelerated BSN", university: "University of Arkansas for Medical Sciences - Northwest", city: "Fayetteville", state: "AR", isPublic: true, programType: "Accelerated BSN", isFlagship: true, tier: "Local", region: "Arkansas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "UAMS Northwest Arkansas campus", dataQuality: "placeholder" },
  { slug: "tx-abilene-christian-university-abilene", name: "BSN", university: "Abilene Christian University", city: "Abilene", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-angelo-state-university-san-angelo", name: "BSN", university: "Angelo State University", city: "San Angelo", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-arizona-college-of-nursing-dallas", name: "BSN", university: "Arizona College of Nursing", city: "Dallas", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-baylor-university-dallas", name: "BSN", university: "Baylor University", city: "Dallas", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: 3.2, minScienceGPA: 3.2, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS","NUTRITION","LIFESPAN","ENGLISH_COMP"], examType: "TEAS", minExamScore: 75, casperRequired: false, deadlines: null, notes: null, dataQuality: "partial" },
  { slug: "tx-chamberlain-college-of-nursing-houston-houston", name: "BSN", university: "Chamberlain College of Nursing – Houston", city: "Houston", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-chamberlain-college-of-nursing-irving-irving", name: "BSN", university: "Chamberlain College of Nursing - Irving", city: "Irving", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-chamberlain-college-of-nursing-pearland-pearland", name: "BSN", university: "Chamberlain College of Nursing – Pearland", city: "Pearland", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-chamberlain-college-of-nursing-san-antonio-san-antonio", name: "BSN", university: "Chamberlain College of Nursing – San Antonio", city: "San Antonio", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-concordia-university-texas-austin", name: "BSN", university: "Concordia University Texas", city: "Austin", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-denver-college-of-nursing-houston", name: "BSN", university: "Denver College of Nursing", city: "Houston", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-east-texas-baptist-university-marshall", name: "BSN", university: "East Texas Baptist University", city: "Marshall", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-fairfield-university-austin", name: "BSN", university: "Fairfield University", city: "Austin", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-galen-college-of-nursing-san-antonio", name: "BSN", university: "Galen College of Nursing", city: "San Antonio", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-hallmark-university-san-antonio", name: "BSN", university: "Hallmark University", city: "San Antonio", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Top TX", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-hardin-simmons-university-abilene", name: "BSN", university: "Hardin-Simmons University", city: "Abilene", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-houston-christian-university-houston", name: "BSN", university: "Houston Christian University", city: "Houston", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-howard-payne-university-brownwood", name: "BSN", university: "Howard Payne University", city: "Brownwood", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-lamar-university-beaumont", name: "BSN", university: "Lamar University", city: "Beaumont", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: 2.5, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM"], examType: "HESI A2", minExamScore: 70, casperRequired: false, deadlines: null, notes: null, dataQuality: "partial" },
  { slug: "tx-letourneau-university-longview", name: "BSN", university: "LeTourneau University", city: "Longview", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Top TX", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "100% NCLEX pass rate (2021).", dataQuality: "placeholder" },
  { slug: "tx-midwestern-state-university-wichita-falls", name: "BSN", university: "Midwestern State University", city: "Wichita Falls", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-patty-hanks-shelton-school-of-nursing-abilene", name: "BSN", university: "Patty Hanks Shelton School of Nursing", city: "Abilene", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-prairie-view-a-m-university-houston", name: "BSN", university: "Prairie View A&M University", city: "Houston", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: 2.5, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","NUTRITION"], examType: "TEAS", minExamScore: 55, casperRequired: false, deadlines: null, notes: null, dataQuality: "partial" },
  { slug: "tx-sam-houston-state-university-the-woodlands", name: "BSN", university: "Sam Houston State University", city: "The Woodlands", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: 2.75, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","STATS","ENGLISH_COMP"], examType: "TEAS", minExamScore: 62, casperRequired: false, deadlines: null, notes: null, dataQuality: "partial" },
  { slug: "tx-schreiner-university-kerrville", name: "BSN", university: "Schreiner University", city: "Kerrville", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-south-university-round-rock", name: "BSN", university: "South University", city: "Round Rock", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-southwestern-adventist-university-keene", name: "BSN", university: "Southwestern Adventist University", city: "Keene", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-st-edward-s-university-austin", name: "BSN", university: "St. Edward's University", city: "Austin", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-st-mary-s-university-san-antonio", name: "BSN", university: "St. Mary's University", city: "San Antonio", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-stephen-f-austin-state-university-nacogdoches", name: "BSN", university: "Stephen F. Austin State University", city: "Nacogdoches", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Top TX", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "DeWitt School of Nursing.", dataQuality: "placeholder" },
  { slug: "tx-sul-ross-state-university-alpine", name: "BSN", university: "Sul Ross State University", city: "Alpine", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-tarleton-state-university-stephenville", name: "BSN", university: "Tarleton State University", city: "Stephenville", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: 2.7, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","STATS","ENGLISH_COMP"], examType: "HESI A2", minExamScore: 70, casperRequired: false, deadlines: null, notes: null, dataQuality: "partial" },
  { slug: "tx-texas-a-m-international-university-laredo", name: "BSN", university: "Texas A&M International University", city: "Laredo", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-texas-a-m-university-bryan", name: "BSN", university: "Texas A&M University", city: "Bryan", state: "TX", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top TX", region: "Texas", minOverallGPA: 3, minScienceGPA: 3, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS","NUTRITION","LIFESPAN","ENGLISH_COMP"], examType: "HESI A2", minExamScore: 75, casperRequired: false, deadlines: "via NursingCAS", notes: "Texas A&M College of Nursing. HESI A2 required (minimum 75% in each section) plus a Kira Talent interview/writing assessment. Verified from official sources (2026).", dataQuality: "verified" },
  { slug: "tx-texas-a-m-university-corpus-christi-corpus-christi", name: "BSN", university: "Texas A&M University Corpus Christi", city: "Corpus Christi", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-texas-a-m-university-texarkana-texarkana", name: "BSN", university: "Texas A&M University Texarkana", city: "Texarkana", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Top TX", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "100% NCLEX pass rate (2021).", dataQuality: "placeholder" },
  { slug: "tx-texas-christian-university-fort-worth", name: "BSN", university: "Texas Christian University", city: "Fort Worth", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Top TX", region: "Texas", minOverallGPA: 3.2, minScienceGPA: 3, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS","NUTRITION","LIFESPAN","ENGLISH_COMP"], examType: "TEAS", minExamScore: 70, casperRequired: true, deadlines: null, notes: null, dataQuality: "partial" },
  { slug: "tx-texas-lutheran-university-seguin", name: "BSN", university: "Texas Lutheran University", city: "Seguin", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-texas-state-university-round-rock", name: "BSN", university: "Texas State University", city: "Round Rock", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Top TX", region: "Texas", minOverallGPA: 2.75, minScienceGPA: 2.75, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS","NUTRITION"], examType: "TEAS", minExamScore: 62, casperRequired: false, deadlines: null, notes: "St. David's School of Nursing (Round Rock).", dataQuality: "partial" },
  { slug: "tx-texas-tech-university-health-sciences-center-school-of-nursing-lubbock", name: "BSN", university: "Texas Tech University Health Sciences Center School of Nursing", city: "Lubbock", state: "TX", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top TX", region: "Texas", minOverallGPA: 3, minScienceGPA: 3, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM"], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "TTUHSC School of Nursing. 3.0 overall and science GPA preferred; holistic review with no TEAS/HESI entrance exam listed. Pathophysiology is also required. Verify current requirements.", dataQuality: "partial" },
  { slug: "tx-texas-tech-university-el-paso-health-sciences-center-el-paso", name: "BSN", university: "Texas Tech University El Paso Health Sciences Center", city: "El Paso", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-texas-woman-s-university-denton", name: "BSN", university: "Texas Woman's University", city: "Denton", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-the-university-of-texas-at-san-antonio-san-antonio", name: "Traditional BSN", university: "UT Health San Antonio", city: "San Antonio", state: "TX", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top TX", region: "Texas", minOverallGPA: 3, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS","NUTRITION","LIFESPAN","ENGLISH_COMP"], examType: "TEAS", minExamScore: 65, casperRequired: false, deadlines: "Feb 1 (Fall) / Aug 1 (Spring)", notes: "UT Health San Antonio School of Nursing. TEAS minimum overall score 65, plus a Kira Talent interview/writing sample. Verified from the official admission page (2026).", dataQuality: "verified" },
  { slug: "tx-university-of-houston-college-of-nursing-sugar-land", name: "BSN", university: "University of Houston College of Nursing", city: "Sugar Land", state: "TX", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top TX", region: "Texas", minOverallGPA: 2.9, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS"], examType: "HESI A2", minExamScore: 75, casperRequired: true, deadlines: null, notes: null, dataQuality: "partial" },
  { slug: "tx-university-of-mary-hardin-baylor-belton", name: "BSN", university: "University of Mary Hardin- Baylor", city: "Belton", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Top TX", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "Scott & White School of Nursing.", dataQuality: "placeholder" },
  { slug: "tx-university-of-north-texas-health-science-center-college-of-nursing-fort-worth", name: "BSN", university: "University of North Texas Health Science Center College of Nursing", city: "Fort Worth", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-university-of-st-thomas-houston", name: "BSN", university: "University of St. Thomas", city: "Houston", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-university-of-texas-at-arlington-arlington", name: "BSN", university: "University of Texas at Arlington", city: "Arlington", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-university-of-texas-at-austin-austin", name: "BSN", university: "University of Texas at Austin", city: "Austin", state: "TX", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top TX", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM","STATS","NUTRITION"], examType: null, minExamScore: null, casperRequired: false, deadlines: "Fall admission only (external transfer)", notes: "UT Austin School of Nursing. Direct-entry BSN, fall admission only. No TEAS/HESI entrance exam required. Highly competitive — admitted students typically have ~3.5+ GPAs. Verify exact prerequisites with the school.", dataQuality: "partial" },
  { slug: "tx-university-of-texas-at-el-paso-el-paso", name: "BSN", university: "University of Texas at El Paso", city: "El Paso", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Top TX", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-university-of-texas-at-tyler-tyler", name: "BSN", university: "University of Texas at Tyler", city: "Tyler", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-university-of-texas-health-science-center-at-houston-houston", name: "BSN", university: "University of Texas Health Science Center at Houston", city: "Houston", state: "TX", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top TX", region: "Texas", minOverallGPA: 3, minScienceGPA: 3, requiredCourses: ["ANAT_PHYS_1","ANAT_PHYS_2","MICRO","CHEM"], examType: "HESI A2", minExamScore: null, casperRequired: false, deadlines: null, notes: "Cizik School of Nursing at UTHealth Houston (flagship). HESI A2 or TEAS required; the entrance exam is waived with a grade of B or better in each pre-nursing science. 3.0 overall and science GPA minimum. Verified from official sources (2026).", dataQuality: "partial" },
  { slug: "tx-university-of-texas-medical-branch-at-galveston-galveston", name: "BSN", university: "University of Texas Medical Branch at Galveston", city: "Galveston", state: "TX", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top TX", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "UTMB Galveston — strong NCLEX outcomes.", dataQuality: "placeholder" },
  { slug: "tx-university-of-texas-of-the-permian-basin-odessa", name: "BSN", university: "University of Texas of the Permian Basin", city: "Odessa", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-university-of-texas-rio-grande-valley-utrgv-edinburg", name: "BSN", university: "University of Texas Rio Grande Valley (Utrgv)", city: "Edinburg", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-university-of-the-incarnate-word-san-antonio", name: "BSN", university: "University of the Incarnate Word", city: "San Antonio", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-wayland-baptist-university-new-braunfels", name: "BSN", university: "Wayland Baptist University", city: "New Braunfels", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-west-coast-university-texas-richardson", name: "BSN", university: "West Coast University Texas", city: "Richardson", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-west-texas-a-m-university-canyon", name: "BSN", university: "West Texas A&M University", city: "Canyon", state: "TX", isPublic: true, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-western-governors-university-houston", name: "BSN", university: "Western Governors University", city: "Houston", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "tx-western-technical-college-el-paso", name: "BSN", university: "Western Technical College", city: "El Paso", state: "TX", isPublic: false, programType: "BSN", isFlagship: false, tier: "Local", region: "Texas", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "pa-university-of-pennsylvania-philadelphia", name: "BSN", university: "University of Pennsylvania", city: "Philadelphia", state: "PA", isPublic: false, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "Top-ranked globally.", dataQuality: "placeholder" },
  { slug: "md-johns-hopkins-university-baltimore", name: "BSN", university: "Johns Hopkins University", city: "Baltimore", state: "MD", isPublic: false, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "Top global / research-intensive.", dataQuality: "placeholder" },
  { slug: "nc-duke-university-durham", name: "BSN", university: "Duke University", city: "Durham", state: "NC", isPublic: false, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "Highly selective top US BSN.", dataQuality: "placeholder" },
  { slug: "wa-university-of-washington-seattle", name: "BSN", university: "University of Washington", city: "Seattle", state: "WA", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "Top public nursing school.", dataQuality: "placeholder" },
  { slug: "nc-university-of-north-carolina-at-chapel-hill-chapel-hill", name: "BSN", university: "University of North Carolina at Chapel Hill", city: "Chapel Hill", state: "NC", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "ga-emory-university-atlanta", name: "BSN", university: "Emory University", city: "Atlanta", state: "GA", isPublic: false, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "Nell Hodgson Woodruff School of Nursing.", dataQuality: "placeholder" },
  { slug: "oh-the-ohio-state-university-columbus", name: "BSN", university: "The Ohio State University", city: "Columbus", state: "OH", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "ia-university-of-iowa-iowa-city", name: "BSN", university: "University of Iowa", city: "Iowa City", state: "IA", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "pa-university-of-pittsburgh-pittsburgh", name: "BSN", university: "University of Pittsburgh", city: "Pittsburgh", state: "PA", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "ma-boston-college-chestnut-hill", name: "BSN", university: "Boston College", city: "Chestnut Hill", state: "MA", isPublic: false, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: "Connell School of Nursing.", dataQuality: "placeholder" },
  { slug: "mi-university-of-michigan-ann-arbor", name: "BSN", university: "University of Michigan", city: "Ann Arbor", state: "MI", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
  { slug: "al-university-of-alabama-at-birmingham-birmingham", name: "BSN", university: "University of Alabama at Birmingham", city: "Birmingham", state: "AL", isPublic: true, programType: "BSN", isFlagship: true, tier: "Top US", region: "National", minOverallGPA: null, minScienceGPA: null, requiredCourses: [], examType: null, minExamScore: null, casperRequired: false, deadlines: null, notes: null, dataQuality: "placeholder" },
]
